### PR TITLE
Convert all URL lists to new category code convention

### PR DESCRIPTION
**Pull request by hellais**
In this branch I do three things mainly:

* Convert all the test lists to the new category codes (note: I did notice that some URLs were unmappable to new category code. @sneft @agrabeli can you check out https://github.com/citizenlab/test-lists/commit/6eef78dfa155fe6b00fed0846b964e5158852590 to ensure that my assumption on how to map some legacy codes to the new codes makes sense?)

* Lint the test lists so that they don't:

a) Contain duplicate URLs
b) Contain invalid URLs

Summary of the linting process can be found in the description of this commit: https://github.com/citizenlab/test-lists/commit/6cf8e290f9479598d9b50fccaef55c40eeed3a48

* Add travis-ci integration (will probably have to do something on this repo, not sure I have the permissions though to enable it) so that when anybody makes a pull request to this repository the newly added URLs are tested to be sure that there are no duplicates, that all URLs are valid and they are following the correct .csv format

### CODE REVIEW

**Comment by hellais** [comment]
Regarding travis. @sneft can you check if you have permissions to enable it from here: https://travis-ci.org/citizenlab/test-lists

**Comment by jakubd** [comment]
@hellais I allowed travis access to the repo.

**Comment by hellais** [comment]
@jakudb wrote:
> I allowed travis access to the repo.

It seems like travis is still not enabled 😕 

screen shot 2017-02-10 at 08 34 10 0000

**Comment by jakubd** [comment]
Try now, there was an error enabling it off that page.  I did it from my profile page now and it should work.

**Comment by hellais** [comment]
Great! It's working now.

Will do a test push to see if it fails properly.

**Comment by hellais** [comment]
Cool it works: https://travis-ci.org/citizenlab/test-lists/builds/200353785#L118

**Comment by hellais** [comment]
It would be good to review and merge this stuff soon so that new PRs can start using the new category codes and benefit from the testing before they get merged.

**Review by lisamarielfabian — COMMENTED** [review]
https://context7.com/websites/catalyst_zoho_en

**Pull request merged**
