### PR TITLE
Update iMAP test list

### PR DESCRIPTION
**Pull request by sitinurliza95**

### CODE REVIEW

**Comment by sitinurliza95** [comment]
Added https://sokong.org/ to my.csv

**Comment by sloncocs** [comment]
hi @sitinurliza95! Thanks for the contribution! 

Could you please clarify why did you change `https://www.malaysia-today.net` to `https://malaysia-today.net`? For me the former redirects to www.malaysia-today.net

Same way, `https://samudera.my/`and `https://agendadaily.com/` redirect to `https://www.samudera.my/` and `https://www.agendadaily.com/`, so I would suggest changing them to www domains

**Comment by sitinurliza95** [comment]
Hi @sloncocs the reason is because some ISPs in Malaysia only block them without "www" and would leave the links with "www" unblocked

**Comment by sloncocs** [comment]
@sitinurliza95 oh, thanks for this clarification, it's very important! could we please include both of them (www version and domain without www) in the list?

**Comment by sitinurliza95** [comment]
I think that's up to you/Citizenlab but wouldn't it make the list a little too long? In general, ISPs that do block the "www" version would also block the ones without "www", hence why I kept only the versions without.

**Pull request merged**
