### PR TITLE
Updated ph.csv

### PR DESCRIPTION
**Pull request by RandomGuy48**
**Removed:**
- http://www.pinoyexchange.com/ _(https://www.rappler.com/technology/internet-culture/pinoyexchange-website-closure-april-15-2023/)_
- http://pinoyhr.net/ _(empty WordPress site)_
- https://cnnphilippines.com/ _(https://www.sunstar.com.ph/tacloban/filipino-journalists-devastated-anew-after-cnn-philippines-shutdown)_
- http://lgbt.ie/ _(national organization in Ireland, irrelevant to ph.csv)_

**Reclassified into CTRL for being inactive**
- http://home.casema.nl/
- http://home.casema.nl/ndf/
- http://buhaymanggagawa.podomatic.com/
- https://bayan.ph/

### CODE REVIEW

**Comment by sloncocs** [comment]
@RandomGuy48 do you think we should keep `http://home.casema.nl/` and `http://home.casema.nl/ndf/` in the list? they have been inactive since 2016, I'd suggest removing these URLs

**Comment by sloncocs** [comment]
same for `https://bayan.ph/` as it hasn't been updated since 2014

**Comment by RandomGuy48** [comment]
Yes, I agree. Both http://home.casema.nl/ & http://home.casema.nl/ndf/ seems to be gone.

I also removed other inactive websites that I labeled CTRL last year from https://github.com/citizenlab/test-lists/pull/1021/commits/03578a35ff7d9a691c7c0710d6879407d431147b
image

I also removed http://www.ihf-hr.org/. It has been previously removed from PR #1614 but has resurfaced again.

Lastly, I would like to ask about where to store the URLs from #1461 
> But at the same time, I think this list of URLs still can be useful for different purposes. So perhaps it would be useful to store these URLs somewhere else before removing them from testing.

**Comment by sloncocs** [comment]
Thanks so much, @RandomGuy48! Regarding the URLs from #1461, unfortunately, we still have no consensus about where to move them. I would say unless there is a huge number of them and they are clearly affecting the number of measurements we receive for other websites, we keep them for the time being.

**Pull request merged**
