### PR TITLE
hk: start adding new entries

### PR DESCRIPTION
**Pull request by bassosimone**

### CODE REVIEW

**Comment by agrabeli** [comment]
Thank you @bassosimone for opening this PR. 

Please replace the content of your file with the following:

https://lihkg.com/,POLR,Political Criticism,2019-07-03,Community member,
http://forum8.hkgolden.com/topics.aspx?type=BW,POLR,Political Criticism,2019-07-03,Community member,
https://thestandnews.com/,NEWS,News Media,2019-07-03,Community member,
https://www.hkcnews.com/,NEWS,News Media,2019-07-03,Community member,
https://www.discuss.com.hk/,POLR,Political Criticism,2019-07-03,Community member,
https://www.baby-kingdom.com/forum.php,XED,Sex Education,2019-07-03,Community member,
https://www.ptt.cc/bbs/index.html,CULTR,Culture,2019-07-03,Community member,
https://www.dcard.tw/,CULTR,Culture,2019-07-03,Community member,
https://www.thisav.com/videos,PORN,Pornography,2019-07-03,Community member,
https://www.gamer.com.tw/,GAME,Gaming,2019-07-03,Community member,

I'm not 100% of the categories (can someone from HK plz review?), but at least by including the above the PR should pass the travis checks (I don't think I can edit the PR directly). 

Given the current situation in HK, we may need to prioritize on merging this PR (cc' @hellais @sneft ) and look into further reviewing the categories at a later stage.

**Comment by sneft** [comment]
I'm happy to review today.

**Comment by bassosimone** [comment]
It seems CI is broken, let me take a look.

**Comment by bassosimone** [comment]
Fixed @sneft !

**Pull request merged**
