### PR TITLE
add full blacklist of blocked gambling sites in switzerland (Comlot and ESBK)

### PR DESCRIPTION
**Pull request by mritzmann**
Access to these websites has been blocked in accord-ance with Art. 86 et seq. of the Federal Act on Gambling and Art. 88 et seq. of the Gambling Ordinance.

source: https://blacklist.comlot.ch/comlot_blacklist_20190903.pdf

### CODE REVIEW

**Comment by mritzmann** [comment]
I just noticed that the Travis check failed. Problem is now fixed.

**Comment by agrabeli** [comment]
Thank you @mritzmann for updating the CH test list. The "source" column is meant to show who added each URL in the test list. Can you please replace "Swiss Lottery and Betting Board (Comlot)" with your name/nick (or "community member")? Thank you. :)

**Comment by mritzmann** [comment]
Hi @agrabeli. Thanks for the info, adapted it. :-)

**Comment by agrabeli** [comment]
@mritzmann excellent, thank you!

**Pull request merged**
