### PR TITLE
Updated PY test list

### PR DESCRIPTION
**Pull request by agrabeli**

### CODE REVIEW

**Comment by agrabeli** [comment]
@hellais @sneft When merging this, please note that another PR for PY has also been opened: https://github.com/citizenlab/test-lists/pull/445

**Comment by hellais** [comment]
@agrabeli the conflicts need to be resolved before merging.

**Comment by agrabeli** [comment]
@hellais @sneft conflict resolved, ready to be merged, I think.

**Comment by hellais** [comment]
lgtm. @sneft can you review and merge?

**Pull request merged**
