### PR TITLE
Add a test list for Lithuania

### PR DESCRIPTION
**Pull request by GiedriusS**
Add a test list for LT (Lithuania). Generated using this hacked together script: https://gist.github.com/GiedriusS/4ba076a7829b8a4c670fa1a63ce77ef1.

### CODE REVIEW

**Comment by hellais** [comment]
Hi @GiedriusS,

Thanks for your interest in contributing to the testing lists!

It seems, however, that all the URLs in this list are just gambling websites.

As we explain in the contribution guidelines (https://ooni.torproject.org/get-involved/contribute-test-lists/), that you should maybe check out if you haven't already, testing lists are **not** block lists.

It would be great if you were to contribute to the lithuania testing list and you should include some gambling websites, but also content from different categories.

**Comment by GiedriusS** [comment]
So, if I understand you correctly, I should add some popular sites in Lithuania that might *more likely* to get blocked from other categories, and not just sites which are blocked already? Is that correct?

**Comment by hellais** [comment]
> So, if I understand you correctly, I should add some popular sites in Lithuania that might more likely to get blocked from other categories, and not just sites which are blocked already? Is that correct?

Yes and perhaps drop some of the gambling websites that are known to be blocked and only include a subset of the ones you suggested in this PR.

**Comment by GiedriusS** [comment]
@hellais hi, sorry for taking a long time but I updated the list according to your request and added 2 political sites which might get blocked soon.

**Comment by GiedriusS** [comment]
@sneft ping.

**Comment by hellais** [comment]
Look good to me, thanks for putting this together!

**Pull request merged**
