### PR TITLE
added new urls

### PR DESCRIPTION
**Pull request by 01123581321345589144233**

### CODE REVIEW

**Comment by agrabeli** [comment]
@linhux thank you for the contributions! I'm not sure though I fully understand what the Keshe Foundation is and does... Can you please share more context? How is it internationally relevant for global testing?

**Comment by linhux** [comment]
keshe foundation as many groups worldwide. thats new technologi for health and energi and other thinks. there is also a education portal https://kfssi.org/ i will also add this to the global list.
For german there is a site kfdeutsch.org, thats can be added on the de.csv
The main site has been manipulatet in few contrys but i have not testet this again.
There are also other local site from keshe, Astria, Poland, Sweden and more. This site can i add to the local csv.

**Comment by hellais** [comment]
I also don't think this website meets the criteria for inclusion in the global testing list.

According to the Alexa ranking (for what it's worth), the site is mostly popular in Iran: https://www.alexa.com/siteinfo/keshe.foundation, but has no relevance on an international level.

I would also like input from @sneft on this, but my vote goes to not including this website in the global testing list as it's unclear what is international relevance of this website.

Moreover the classification of `PUBH,Public Health` is quite misleading as the site appears to be mostly related to pseudo-scientific conspiracy theories.

**Comment by linhux** [comment]
ok the domain keshe.foundation are new and the main site since 2015 is
https://www.alexa.com/siteinfo/keshefoundation.org

**Comment by sneft** [comment]
Thanks @hellais. I've also reviewed and don't think that Keshe Foundation warrants addition to the testing lists. Are there any known instances of this site being blocked?

**Comment by agrabeli** [comment]
As reviewers consider that Keshe Foundation doesn't warrant testing and there has been no reference (in over a year) of known cases of blocking, I'll be closing this PR.

**Pull request closed without merging**
