### PR TITLE
adicionando algumo sites ativistas importante

### PR DESCRIPTION
**Pull request by opensamba**
Hi / Oi

acho que seria bom adicionar esses sites na lista brasileira , tem ativismo, codingrights, terra dos direitos e outros
a lista precisarie  de mais web, em breve vai chegare eleicoes e seria bom mapear tudo.
mais por agora vamos por ai!

bye

Hi,
I propose to add a couple of new website, like ativismo codingrights terra dos dereitos
there should be more, as election in brasil is about to arrive next year
but for now let's keep this update like this!

### CODE REVIEW

**Comment by hellais** [comment]
Hi, can you fix the formatting of the URLs?

The CI is failing, copy pasting here the error:

```
lists/br.csv (line 2769): Invalid Column Number
lists/br.csv (line 2770): Invalid Column Number
lists/br.csv (line 2771): Invalid Column Number
lists/br.csv (line 2772): Invalid Column Number
```

**Comment by opensamba** [comment]
ehm, ok maybe I missed some comma?

how do I make the change and test everything works fine, should I install and configure travis locally ?

**Comment by hellais** [comment]
You can run it locally by doing:
```
python scripts/lint-lists.py lists/
```

**Comment by hellais** [comment]
I see this has now diverged from master quite a bit.

It's probably useful to open a new PR with only the desired URLs in it:
```
http://terradedireitos.org.br/,2017-12-21,Human Right defendere, samba,
https://ativismo.org.br,2017-12-21,NGO in Brazil,samba,
https://www.codingrights.org,2017-12-21, translating human rights into code, samba,
https://www.chupadados.com,2017-12-21, list of abusive and monitoring technologies in brazil,samba,
```

**Comment by hellais** [comment]
Closing this in favour of: https://github.com/citizenlab/test-lists/pull/461

**Pull request closed without merging**
