### PR TITLE
Added news websites blocked today

### PR DESCRIPTION
**Pull request by agharbeia**
These websites are blocked as of today, only one ISP in Egypt seems to be unaffected by the blockage. The websites are accessible via proxy at the time of this request.

### CODE REVIEW

**Comment by hellais** [comment]
LGTM

**Comment by anadahz** [comment]
> These websites are blocked as of today, only one ISP in Egypt seems to be unaffected by the blockage. 

@agharbeia Do you know which ISP seems to not be affected by the blockage?

**Comment by agharbeia** [comment]
It's http://noor.net again
AlMasry AlYoum published a report by an unnamed security agency, i.e intelligence, justifying the action and citing similar cases in other countries, and claiming it as a step against terrorism: http://www.almasryalyoum.com/news/details/1139015
I can access one site through https, while others say they cannot!

**Comment by anadahz** [comment]
@agharbeia thanks for the heads up!

Do you think that the domains included here are relevant (?): https://github.com/citizenlab/test-lists/pull/164

**Comment by agharbeia** [comment]
@anadahz, the domains added in #164 are also relevant. Thanks.

**Pull request merged**
