### PR TITLE
List updates

### PR DESCRIPTION
**Pull request by glamrock**
Just some corrections to the lists, as I kept running into 301/302/307 issues when scanning these normally.  I'll make more changes as the week progresses, but am working with a deadline on other things.

### CODE REVIEW

**Comment by glamrock** [comment]
^ bump

**Comment by hellais** [comment]
Hi Griffin,

Thanks for this. Looking at the diff this looks good to me, though could you rebase it with the current master so we can merge it cleanly?

**Comment by NHellFire** [comment]
Bump. Still needs a rebase.

**Comment by hellais** [comment]
I am closing this due to inactivity. Please file a new PR if you would still like to contribute them.

**Pull request closed without merging**
