### PR TITLE
updated bangladesh local list

### PR DESCRIPTION
**Pull request by sneft**
I've added all the active sites listed in this article: 
https://www.thedailystar.net/country/news/btrc-withdraws-block-58-sews-sites-1671769

### CODE REVIEW

**Comment by hellais** [comment]
Good call, with @agrabeli we were also looking into this just now.

There are a couple more of them, though too:
```
http://www.sangbad247.com/
https://www.awaazbd.com/
http://bnpbangladesh.com/
https://diganta.net/
http://dailybdtimes.com/
http://razniti24.com/
http://badrul.org
https://millateibrahimbd.wordpress.com/
https://www.banglastatus.com/
http://www.deshnetricyberforum.com/
https://defenseupdatebangladesh.wordpress.com/
http://bbarianews24.com
http://www.analysisbd.com/
http://cnnbd24.com/
https://alehsar2.wordpress.com/
http://www.potryka.com/
http://news21-bd.com/
https://jongimedia.wordpress.com/
https://bangladarsulquran.wordpress.com/
https://maktabatulislamiabd.wordpress.com/
http://deshbhabona.com
http://1newsbd.net/
http://www.mymensinghnews24.com/?from=@
http://dailymirror24.com
http://bnponlinewing.com/
http://www.moralnews24.com/
http://myquranstudyoneayahaday.com
http://en.bnpbangladesh.com/
http://www.atv24bd.com/
http://pagenews24.com
http://dnn.news/
https://shuhadarkafela.wordpress.com/
http://www.justnewsbd.com/
http://www.expressnewsbd.com/
http://reportbd24.com
http://ww1.rarenews24.com
https://www.prothombangladesh.net/
http://www.rbn24.co.uk/
https://dawahilallah.com/
https://amardesh247.com/
http://bnpnews24.com/
http://sheershanews24.com/
http://newsbd71.com/
http://www.muldharabd.com/
http://alapon.live
https://www.defbd.com/
http://shibir.org.bd/
https://aljamaah1.wordpress.com/
http://dailyamardesh.xyz/
http://gazwah.net/
https://bangladeshdefence.blogspot.com/
https://bdpolitico.com/
http://banglamail71.info/
```

Did you omit some of these from the PR because some of them were down or no longer active?

**Comment by sneft** [comment]
Yes, I went with the active URLs. I looked up some in the wayback machine and it was hard to find any legit content. Convention says we should add them anyway, though.

Also - I am unclear of the context around these, and am aware the rationale for them being blocked is that they were spreading misinformation, so if there's any reason that NEWS category is inappropriate that should change too.

**Comment by agrabeli** [comment]
@sneft thanks so much for adding these! I think categorizing them as NEWS is probably fine (can't think of a better category for them atm).

**Comment by hellais** [comment]
I am going to merge this so that @agrabeli can add some other URLs on top of it.

**Pull request merged**
