### PR TITLE
Update dz.csv

### PR DESCRIPTION
**Pull request by BoFFire**
Adding two 2 algerian media websites  :
* L'avant Garde
* Le Matin d'Algérie

Reportedly censored to algerian internet users.

* Source : https://www.lorientlejour.com/article/1218208/un-nouveau-site-dinformation-bloque-en-algerie.html
* Source : https://rsf.org/fr/actualites/algerie-quand-les-autorites-sacharnent-sur-les-medias-au-lieu-de-lutter-contre-la-pandemie

### CODE REVIEW

**Comment by agrabeli** [comment]
Thank you @BoFFire !

@jakubd @hellais do you perhaps know why the CI checks are failing?

**Comment by BoFFire** [comment]
Hi @agrabeli
May be because I deleted the last white/blank line ?

**Comment by hellais** [comment]
```
Analyzed 32937 URLs in 142 countries
1 errors present
lists/dz.csv (line 143): Duplicate URL "https://www.lematindalgerie.com/"
##[error]Process completed with exit code 1.
```

**Comment by BoFFire** [comment]
Thanks @hellais ^-^
My bad. Duplicate.

**Comment by agrabeli** [comment]
Thank you @BoFFire !

**Pull request merged**
