### PR TITLE
Updated global

### PR DESCRIPTION
**Pull request by eddie4**
Added leechers-paradise.org which is an openbittorrent tracker.  Tracker is used for downloading anything and everything. from Linux to probably copyrighted material.

### CODE REVIEW

**Comment by eddie4** [comment]
Hmm seems i found an old page with wrong catagories. Can't find where i found it tho.

**Comment by hellais** [comment]
I think we already have a fairly representative sample of torrent related websites in the global testing list.

Given the fact that this site is ranked by alexa as number "409,665" I think it's hard to justify including it inside of the global testing list.

That said it seems like it's pretty popular in India, so maybe it could be considered for inclusion in the India test list.

**Comment by eddie4** [comment]
I have no clue how alexa calculates the popularity. But it's not so much the website that is interesting but the service that is running on udp port 6969. This service has 50 million unique visitors a day. It burns through almost 4TB a day of 10kbit of requests. 

It is currently actively banned in Russia and south afrika (That i know of)
The following sites are the backbone of the bittorrent network (yes i know DHT is a thing)
tracker.coppersurfer.tk
tracker.leechers-paradise.org
zer0day.ch
open.demonii.com 
exodus.desync.com

**Comment by hellais** [comment]
> But it's not so much the website that is interesting but the service that is running on udp port 6969.

I see. If that is the case, then adding it to the test list will not yield the desired result.

I can see there being quite some value in having tests also for UDP reachability and in particular for torrent trackers.

As such I filed this ticket in measurement-kit, the library that implement OONI tests: https://github.com/measurement-kit/measurement-kit/issues/1546.

I think we would gladly accept a patch implementing some test of this type and having as one of the tested trackers be `leechers-paradise.org`.

**Comment by eddie4** [comment]
That would be even more awesome. Having actual logic to detect higher level messing with traffic.

**Comment by hellais** [comment]
> That would be even more awesome. Having actual logic to detect higher level messing with traffic.

Excellent. I am going to close this PR as we have the other ticket open about this. Thanks for your interest!

**Pull request closed without merging**
