### PR TITLE
Eco site blocked in Belarus

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by sloncocs** [comment]
Thank you for your contribution @abitrolly! I changed the category of https://greenbelarus.info/ from NEWS to ENV as it is an ecological project. Merging the PR now.

**Comment by abitrolly** [comment]
@sloncocs thanks. I could not find the list of categories, so I just copied the closest. I remember the categories were on the front page somewhere, but now there is only explanatory content.

**Comment by sloncocs** [comment]
@abitrolly the full list of categories can be found here: https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv, and general recommendations on the test lists review process here: https://ooni.org/get-involved/contribute-test-lists/ 🙏

**Comment by abitrolly** [comment]
I saw general recommendations. The link to list of categories is hard to find.

**Pull request merged**
