### PR TITLE
Create test list for Uruguay

### PR DESCRIPTION
**Pull request by hellais**
Creating this pull request for the addition of the test list from @asterismo.

Original comment from his commit is:

> These are a collection of URLs worth testing for country code UY

In order to make this mergable the following fixes need to be made:
- [ ] The columns need to be 6 (url,category_code,category_description,date_added,source,notes). What is now the url_description column should probably go inside of the notes section.
- [ ] Change the blogspot URLs to be the canonical .com version (I think it's more likely that these are blocked rather than their `.uy` equivalent). This is a non blocker though.

### CODE REVIEW

**Comment by hellais** [comment]
@asterismo I saw on IRC you were asking about using the new categories and in such case where should the NEWS sites go. I think they now will fit under the `FEXP` category, though perhaps @agrabeli has more insight into the suggested category for these ones.

At some point I will anyways automatically migrate all the old ones to new categories automatically, so it's not a big deal to change it, though if there is something more appropriate than `FEXP` we should fix it now.

**Comment by asterismo** [comment]
Ok, thanks for the comments, i'll add the missing categories and fields and submit a new list maybe this night.

**Comment by hellais** [comment]
@agrabeli do you think it's useful to integrate these into the uruguay test list? Maybe to have Derechos digitales look at it?

**Comment by gabelula** [comment]
Hey! You can add all this other sites to this PR:

https://www.elobservador.com.uy/,news,News Media, 2019-04-18,Mainstream Media
https://ladiaria.com.uy/,news,News Media, 2019-04-18,Mainstream Media
https://ecos.la/,news,News Media, 2019-04-18,Mainstream Media
http://www.elbocon.com.uy/,news,News Media, 2019-04-18,Mainstream Media
https://www.cronicas.com.uy,news,News Media, 2019-04-18,Mainstream Media
http://www.uypress.net/,news,News Media, 2019-04-18,Mainstream Media
https://180.com.uy/,news,News Media, 2019-04-18,Mainstream Media

**Comment by gabelula** [comment]
and be careful because there are conflicts and uy.csv in the repo now includes many of news sites that should be tested.

**Comment by hellais** [comment]
Yes I think this PR should be closed and a new one created with relevant URLs from this one and possibly new ones.

@gabelula could you look into filing a new PR for the `uy.csv` list?

**Comment by gabelula** [comment]
ok. I can do that today.

**Comment by gabelula** [comment]
Done. The new PR is here https://github.com/citizenlab/test-lists/pull/457

**Comment by asterismo** [comment]
Oh, glad to see some activity here. Maybe some of the original URLs are offline by now. Cheers!

**Pull request closed without merging**
