### PR TITLE
Added Aljazeera to global list

### PR DESCRIPTION
**Pull request by agrabeli**
Aljazeera appears to have 2 domains: aljazeera.net & aljazeera.com. 

As part of this PR, I added aljazeera.com to the global test list and fixed the URL for aljazeera.net.

### CODE REVIEW

**Comment by agrabeli** [comment]
@sneft Merging #511 is a prerequisite to merging this PR.

**Comment by agrabeli** [comment]
Hm, I'm wondering why the Travis CI build is still failing, given that the issues have been fixed with #511 which has been merged....

**Comment by agrabeli** [comment]
@hellais @sneft To delete duplicates (between the global test list and local ones), I opened another PR (#511) which has been merged. I would therefore assume that the checks for this PR should pass, but they don't. How can we make Travis re-process the PR once another PR - which addresses the failed checks - has been merged?

**Comment by sneft** [comment]
I think the issue is that Travis processing only the files contained within your PR, which will technically still contain the duplicate URLs in the local lists since #511 was only merged afterwards. Since there are no conflicts with the base branch, I'm under the impression that if we were to merge this right now it would only add the URLs to the global list and wouldn't change the 3 local lists. 

I think the alternative is for you to update your fork and submit another PR updating this one, which should reflect the changes made to the local lists?

**Comment by agrabeli** [comment]
> Since there are no conflicts with the base branch, I'm under the impression that if we were to merge this right now it would only add the URLs to the global list and wouldn't change the 3 local lists.

@sneft Yes, I have the same impression. Should we try merging this PR?

**Pull request merged**
