### PR TITLE
Update tz.csv

### PR DESCRIPTION
**Pull request by Sylviakanari**

### CODE REVIEW

**Comment by hellais** [comment]
Thanks for contributing to the test lists! 

This looks good me. Merging.

**Comment by anadahz** [comment]
@hellais this PR has some URL errors that need to be resolved first, please revert the merge.

**Comment by hellais** [comment]
> @hellais this PR has some URL errors that need to be resolved first, please revert the merge.

Which errors? The CI is passing.

**Comment by anadahz** [comment]
> Which errors? The CI is passing.

1. The link 'http://cdftz.org/page.php?pg=128/' doesn't exist (in
https://github.com/citizenlab/test-lists/pull/496/commits/0ee0286ceea2910dea044264b38d99862230f38d#diff-308fc02f81df9786d51670defb914e6aR2),
perhaps you can use only the domain name (`http://cdftz.org/`) instead?

2. Only domain names need a backslash at the end and not full URLs. The
following URLs do **not** require to end with a backslask ('/'):
* http://fgcdailynews.blogspot.com/2010/11/tanzania-anti-mutilation-campaign.html
* http://madikazemi.blogspot.com/2009/07/activists-petition-un-over-violation-of.html
* http://mpayukaji.blogspot.com/2011/02/suto-kwa-wadini-wa-tanzania-ufisadi.html
* http://news.bbc.co.uk/2/hi/africa/7523796.stm
* http://thecitizen.co.tz/news/4-national-news/5861-police-alleged-to-delaymurder-case-of-tabora-albino-girl.html
* http://www.chadema.or.tz/index.php
* http://www.gayegypt.com/tanzania.html
* www.iglhrc.org/cgi-bin/iowa/home/index.html
* http://www.npr.org/2011/06/22/137342470/-un-recognizes-gay-rights-as-human-rights
* http://www.socialistworker.co.uk/art.php?id=24948
* http://www.stanhopecentre.org/training/EA/zelamula_seminar.shtml
* http://www.state.gov/g/drl/rls/hrrpt/2009/af/135980.htm

3. The following entries have been accidentally removed (previously in the
Tanzanian test-list). Usually test-list entries are not removed except if there
is a good reason to do so:
* http://www.bbc.com/swahili/
* http://www.bbcswahili.com/
* https://sw.wikipedia.org/

4. Are the following websites only used in Tanzania or do they have a significant meaning to the internet users of Tanzania?:
* http://zedo.com/
* http://www.onclickads.net/
* http://myway.com/
* http://livescore.com/


5. The following URLs are already in the global test-list and they don't need to
be added in a country specific test-list. By default OONI Probe tests the global
and regional test lists running from a given country.
* http://savefrom.net/
* http://doubleclick.net/
* http://xhamster.com/
* http://extratorrent.cc/
* http://twitter.com/
* http://facebook.com/

6. The following domains/URLs seem to not serve any content, do you think that
are necessary for the Tanzanian test list?
* http://blkget.com
* http://iwanttodeliver.com/
* http://offerreality.com/
* http://rahatupu.blogspot.com/
* http://www.maswayetublog.com/
* http://clevernt.com/
* https://thewhizmarketing.com/
* http://hottestgirlsclub.com/
* http://williammalecela.com/
* http://djchokamusic.com/
* http://ajirayako.com/
* http://siasahuru.com

7. There are multiple Facebook URLs, test-lists usually check websites based on
the domain name so it's not so useful to add multiple links of the same domain.
* https://www.facebook.com/tanzagiza/
* https://www.facebook.com/edo.kumwembe/
* https://www.facebook.com/zittokabwe/
* https://www.facebook.com/JamiiForums/

The same applies also to the following entries:
* http://kenyangayman.wordpress.com/2011/01/25/tanzania-gay-movie/
* http://mpayukaji.blogspot.com/2011/02/suto-kwa-wadini-wa-tanzania-ufisadi.html/
* http://thecitizen.co.tz/news/4-national-news/5861-police-alleged-to-delaymurder-case-of-tabora-albino-girl.html/
* http://moe.go.tz/sw/
* http://thecitizen.co.tz/news/4-national-news/5861-police-alleged-to-delaymurder-case-of-tabora-albino-girl.html/

**Comment by hellais** [comment]
@anadahz ah good call. Can you file a new PR with the fixes for these URLs?

**Comment by anadahz** [comment]
@hellais it's a (WIP) learning process of updating test-lists.
Please revert the PR and @Sylviakanari will update/fix/review the TZ test-list.

**Comment by hellais** [comment]
> Please revert the PR and @Sylviakanari will update/fix/review the TZ test-list.

You can do the revert of the commit in question and the fixes inside of the same PR. I will be glad to review it once it's ready.

**Comment by anadahz** [comment]
> You can do the revert of the commit in question and the fixes inside of the same PR. I will be glad to review it once it's ready.

OK, as a reminder at its current state the TZ test-list in the repo is broken.

**Comment by hellais** [comment]
I have reverted this commit and pushed to master. I would have preferred to have done it all in one go (I assumed you had some script to generate that list above and had it ready, though I suppose not).

I hope we don't forget about this PR and adding the URLs contained in here.

**Comment by agrabeli** [comment]
@hellais @anadahz @Sylviakanari Hello! I worked on updating the TZ test list because the latest version (https://github.com/citizenlab/test-lists/blob/master/lists/tz.csv) suggested that the list hadn't really been updated since 2014, and I hadn't seen this PR (particularly since it was merged).

I then opened this pull request which contains many updates: https://github.com/citizenlab/test-lists/pull/520

If I understand the conversation in this thread, a new PR with @Sylviakanari's updates needs to be opened?

**Comment by agrabeli** [comment]
@hellais @anadahz I have added all of @Sylviakanari 's updates (and I've addressed @anadahz's feedback) in my latest commit in PR https://github.com/citizenlab/test-lists/pull/520.

@Sylviakanari thank you for the great work! :)

**Comment by Sylviakanari** [comment]
Thanks Maria. It has been a great learning process for me.

Sylvia

**Pull request merged**
