### PR TITLE
Updates to Indonesian and Malaysian Lists

### PR DESCRIPTION
**Pull request by kaerumy**
* Add sites related to West Papua (id)
* Add US Department of Justice 1MDB court filing (my)
* Add patheos.com a religious site reportedly blocked (my)

### CODE REVIEW

**Comment by hellais** [comment]
There some issues with this PR:

```
lists/my.csv (line 58): Invalid Column Number
lists/my.csv (line 59): Invalid Column Number
lists/my.csv (line 215): Duplicate URL "http://www.financetwitter.com"
lists/my.csv (line 342): Duplicate URL "http://sprminsider.blogspot.com"
```

**Comment by hellais** [comment]
This still needs some rebasing.

**Comment by kaerumy** [comment]
Rebased with latest upstream and reordered new additions to id.csv alphabetically

**Comment by hellais** [comment]
It looks like the branch still doesn't merge cleanly with master. @kaerumy can you look into it?

**Comment by hellais** [comment]
I cherry picked the commit and manually applied the other changes I could spot in: https://github.com/citizenlab/test-lists/pull/225. @kaerumy and @sweemeng can you check if I missed anything?

**Comment by sweemeng** [comment]
It is ok on my side, let see what @kaerumy says

**Comment by kaerumy** [comment]
Looks good to me. It's the older id (Indonesia) entries I think that was problematic in merging. I see they've added now manually. Thanks for doing this, those Indonesian entries were more important, as it relates to possible censorship of West Papua news and sites.

**Pull request closed without merging**
