### PR TITLE
Update cn.csv

### PR DESCRIPTION
**Pull request by tomac4t**
- Anonymization and circumvention tools `Alexa ranks`
~https://www.uproxy.org/ `#4,919,659`~ (Moved to global list.)
~https://getlantern.org/ `#84,982`~ (Moved to global list.)
~https://getoutline.org/ `#180,667`~ (Duplicated)
- Search Engines
https://searx.me/ `#183,666`
(There is a list about Public Searx instances: https://asciimoo.github.io/searx/user/public_instances.html)
- Social Networking
~https://joinmastodon.org/ `#97,279`~ (Moved to global list.)
https://mastodon.cloud/ `#109,181`
https://mastodon.host/ `#814,718`
~https://mastodon.social/ `#27,011`~ (Moved to global list.)
https://mastodon.xyz/ `#1,350,963`
https://g0v.social/ `#8,057,716`
https://niu.moe/ `#1,190,865`
https://bangdream.space/ 
https://cmx.im/ `#1,668,764`
https://mstdn.io/ `#603,384`
(The federated social network lists: https://the-federation.info/ https://fediverse.network/ etc.)
- News Media
http://www.ftchinese.com/ `#5,380`
http://www.sputniknews.cn/ `#27,471`
~https://www.aljazeera.com/ `#4,114`~ (Duplicated)
https://www.dailysabah.com/ `#24,977`
https://www.dailymail.co.uk/ `#257`
~https://www.theguardian.com/ `#133`~ (Duplicated)
https://www.economist.com/ `#3,106`
https://www.theatlantic.com/ `#1,879`
https://www.nbcnews.com/ `#687`

### CODE REVIEW

**Comment by tomac4t** [comment]
```
----------
Analyzed 32442 URLs in 142 countries
3 errors present
lists/cn.csv (line 490): Duplicate URL between Local List and Global List "https://getoutline.org/"
lists/cn.csv (line 504): Duplicate URL between Local List and Global List "https://www.aljazeera.com/"
lists/cn.csv (line 507): Duplicate URL between Local List and Global List "https://www.theguardian.com/"
The command "python scripts/lint-lists.py lists/" exited with 1.
```
Look like I should delete them....

**Comment by tomac4t** [comment]
> I think that all of the URLs in this PR need to be added to the global test list (which will be tested by OONI Probe users in China as well), except for URLs like g0v.social and cmx.im. 
Those URLs are blocked in China (except ftchinese.com, which unblocked recently).

[asciimoo/searx](https://github.com/asciimoo/searx) is an interesting project, that everyone could build their own meta-search engine. [The official instance](https://searx.me/) is down now, I don't know when it will online again. Maybe I should add other instances like https://search.privacytools.io/ ?

Some of the above Mastodon instances are Chinese-specific, like https://g0v.social/ (Taiwan owner) https://cmx.im/ (which you mentioned) https://bangdream.space/, I don't want to add the to the global list. I also want to add PeerTube and PixelFed instances to global, test them will be interesting.

> Perhaps even ftchinese.com can go to the global test list.

I will. Another question is if I need to create a new Pull Request and add them to global? @agrabeli

**Comment by tomac4t** [comment]
https://github.com/citizenlab/test-lists/blob/1699832de774e578f7a7f3bee4d2be75efa2aca8/lists/global.csv#L987

Note: http://www.stupidcensorship.com/ is parking page now, should be removed?

**Comment by agrabeli** [comment]
> [The official instance](https://searx.me/) is down now, I don't know when it will online again. Maybe I should add other instances like https://search.privacytools.io/ ?

That would be great, thanks!
 
> Some of the above Mastodon instances are Chinese-specific, like https://g0v.social/ (Taiwan owner) https://cmx.im/ (which you mentioned) https://bangdream.space/, I don't want to add the to the global list. I also want to add PeerTube and PixelFed instances to global, test them will be interesting.

Those sound like great additions to the global test list.

> I will. Another question is if I need to create a new Pull Request and add them to global?

Yes, a new PR with further updates to the global test list would be ideal. 

Thanks so much for your time and contributions!

**Comment by tomac4t** [comment]
New PR #579.

**Pull request closed without merging**
