### PR TITLE
Add a few more URLs to identify hidden censorship

### PR DESCRIPTION
**Pull request by xhdix**
Because some ISPs seek to destroy the popularity of services instead of censoring them, they only target CDN addresses.
(Pinterest, Reddit, Quora, Wikipedia, GitHub, GitLab, StackOverflow, Instagram, Mozilla, Google)

### CODE REVIEW

**Comment by xhdix** [comment]
[OONI test for recent list.](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fupload.twitter.com%2Frobots.txt%22%2C%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F941658150889054208%2FlFeD3554_200x200.jpg%22%2C%22https%3A%2F%2Fvideo.twimg.com%2Ftweet_video%2FEC6DSXDXsAEhHAa.mp4%22%2C%22https%3A%2F%2Fajax.aspnetcdn.com%2Fajax%2F4.5.2%2F1%2FMicrosoftAjax.js%22%2C%22https%3A%2F%2Flh3.ggpht.com%2F_mm3cDcdhxkc%2FSzkPLt_zDUI%2FAAAAAAAAAZM%2FUplZlTSCVQc%2Fs800%2FDSC_5305.jpg%22%2C%22https%3A%2F%2Flh4.ggpht.com%2F_PvLDsC2pRvk%2FShwiscZujVI%2FAAAAAAAAFIQ%2F4q-TYiQ13-k%2Fs512%2FDSC01330.jpg%22%2C%22https%3A%2F%2Fabs.twimg.com%2Fsticky%2Fdefault_profile_images%2Fdefault_profile_normal.png%22%2C%22https%3A%2F%2Fyt3.ggpht.com%2Fa-%2FAOh14GhGCI1dxtHOY_TDQfmxDBK_S7CHTPJ3U6zOUw%3Ds480-c-k-c0x00ffffff-no-rj-mo%22%2C%22https%3A%2F%2Fyt4.ggpht.com%2Fa-%2FAOh14GhOiUxI-RcMC-Vfl2i15v3xewMr8bt2yNXTfw%3Ds480-c-k-c0x00ffffff-no-rj-mo%22%2C%22https%3A%2F%2Fi.ytimg.com%2Fvi%2FJBRf3nEqfZ8%2Fhq720.jpg%22%2C%22https%3A%2F%2Fi.pinimg.com%2F236x%2F78%2F6e%2F00%2F786e00eab219eca59803d118fbe0feb3.jpg%22%2C%22https%3A%2F%2Fs.pinimg.com%2Frobots.txt%22%2C%22https%3A%2F%2Fstyles.redditmedia.com%2Frobots.txt%22%2C%22https%3A%2F%2Fpreview.redd.it%2Frobots.txt%22%2C%22https%3A%2F%2Fwww.redditstatic.com%2Frobots.txt%22%2C%22https%3A%2F%2Fqsbr.fs.quoracdn.net%2F-4-web.entry.js.out-34-8f7d03da0b7a24ae.webpack%22%2C%22https%3A%2F%2Fqph.fs.quoracdn.net%2Fmain-thumb-1117688072-200-uijiqfjcmlvaxczdrlawbgyaomfocdnt.jpeg%22%2C%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FWikidata%3AMain_Page%22%2C%22https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fd%2Fd1%2FMarine_animals_and_their_associated_microbiomes.jpg%22%2C%22https%3A%2F%2Fdocs.github.com%2Fen%22%2C%22https%3A%2F%2Fapi.github.com%2F_private%2Fbrowser%2Fstats%22%2C%22https%3A%2F%2Fgithub.githubassets.com%2Fimages%2Fmodules%2Fopen_graph%2Fgithub-logo.png%22%2C%22https%3A%2F%2Fraw.githubusercontent.com%2Fooni%2Fspec%2Fmaster%2FREADME.md%22%2C%22https%3A%2F%2Fgist.github.com%2Fdiscover%22%2C%22https%3A%2F%2Fooni.github.io%2F%22%2C%22https%3A%2F%2Fgit.io%2F%22%2C%22https%3A%2F%2Fcodeload.github.com%2Fgithub%2Frally%2Ftar.gz%2Fv1.0.1%22%2C%22https%3A%2F%2Fgithub.com%2Ftwbs%2Fbootstrap%2Freleases%2Fdownload%2Fv4.5.3%2Fbootstrap-4.5.3-examples.zip%22%2C%22https%3A%2F%2Ffedoramagazine.org%2F%22%2C%22https%3A%2F%2Fassets.gitlab-static.net%2Frobots.txt%22%2C%22https%3A%2F%2Fcdn.sstatic.net%2FImg%2Fhome%2Fopen-source.svg%22%2C%22https%3A%2F%2Fi.instagram.com%2Frobots.txt%22%2C%22https%3A%2F%2Fscontent-ams4-1.cdninstagram.com%2Frobots.txt%22%2C%22https%3A%2F%2Fstatic.xx.fbcdn.net%2Frobots.txt%22%2C%22https%3A%2F%2Fedge-chat.instagram.com%2Frobots.txt%22%2C%22https%3A%2F%2Fcode.jquery.com%2F%22%2C%22https%3A%2F%2Fblog.mozilla.org%2F%22%2C%22https%3A%2F%2Fdownload-installer.cdn.mozilla.net%2F%22%2C%22https%3A%2F%2Fdl.google.com%2Frobots.txt%22%2C%22https%3A%2F%2Fwww.gstatic.com%2Frobots.txt%22%5D%7D&mv=1.2.0)

**Comment by xhdix** [comment]
@hellais, review please!

**Comment by bassosimone** [comment]
@hellais I think we should merge this PR: we tested with @xhdix and it's fine!

**Comment by agrabeli** [comment]
Thank you @xhdix for opening this PR, and sincere apologies for the huge delay. :( Merging now!

**Comment by mimi89999** [comment]
Anyway, those sites have HTTPS, so the censor only knows the domain of the website, but not the full URL.

**Comment by xhdix** [comment]
@mimi89999 I agree with you, but there are two more important issues:
1. Avoid receiving HTTP error
2. Detect some censorship techniques that have been documented (such as bandwidth-throttling) and have not yet been documented (in progress).

**Pull request merged**
