### PR TITLE
Czech Republic censorship list

### PR DESCRIPTION
**Pull request by ja-pa**
This list contains gambling sites blocked by Czech ISP on the basis of the regulation by Ministry of Finance of the Czech Republic

### CODE REVIEW

**Comment by ja-pa** [comment]
List provided by Ministry of Finance (in pdf format) https://www.mfcr.cz/cs/soukromy-sektor/hazardni-hry/seznam-nepovolenych-internetovych-her

**Comment by agrabeli** [comment]
@ja-pa this is great, thank you! 

We generally try to ensure that test lists include a diverse set of URLs that fall under these 30 categories: https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv

It would be great if you could propose additional URLs from other categories to help enrich the Czech test list. Thank you!

**Comment by ja-pa** [comment]
Hi,
I have updated the list of censored gambling sites and added several Czech sites from different categories to make the test list more diverse.
@agrabeli  Please let me know if these changes are ok.

**Comment by ja-pa** [comment]
@hellais , @agrabeli Please check my changes.

**Comment by agrabeli** [comment]
@hellais @sneft Do you perhaps have a script for automatically adding all the missing slashes (see Travis failed checks)?

**Comment by agrabeli** [comment]
@ja-pa Thank you for your contributions, and sincere apologies for the delay in following through with this. The "source" column is meant to show who added each URL. Can you please add the relevant name or nick (or even just "community member") for all rows in the source column? Thanks a million!

**Comment by ja-pa** [comment]
@agrabeli Hi, I updated PR and replace source with my nickname, add 4 new blocked domains and squash all commits to one. Feel free to let me know if there is something missing. Thanks :-)

**Comment by agrabeli** [comment]
Thanks a million @ja-pa , this is great!

**Pull request merged**
