### PR TITLE
Added 1 url

### PR DESCRIPTION
**Pull request by Tafiti**

### CODE REVIEW

**Comment by sneft** [comment]
I notice that this URL 404's. Has it been moved elsewhere? Could you add more context?

**Comment by Tafiti** [comment]
Turns out that url has been brought down by the media company.
This may help us understand trends around self-censorship. It was reporting on state procurement of Internet surveillance equipment.

Should we keep the url on the list?

**Comment by hellais** [comment]
> Turns out that url has been brought down by the media company.

I checked on archive.is and it seems like the URL was not archived. I think it would be a best practice to always archive these URLs via http://archive.is/ when they are added, perhaps we could even do this automatically.

> This may help us understand trends around self-censorship. It was reporting on state procurement of Internet surveillance equipment.
> Should we keep the url on the list?

I am not sure if at this point it makes sense to add it to this particular testing list, since we don't really care to have users check the reachability of it. It maybe interesting, though, to start some other list repository for storing these sorts of URLs (with the connected archive.is snapshotting of the URL).

**Comment by Tafiti** [comment]
I like the idea of using archive.is to capture the moment in time. 

Also, worth checking [this](https://petertodd.org/2017/carbon-dating-the-internet-archive-with-opentimestamps) idea by @petertodd on timestamping archive.is.

**Pull request closed without merging**
