### PR TITLE
Removed duplicate URLs from various country lists

### PR DESCRIPTION
**Pull request by RandomGuy48**
Updated `www.heritage.org`, `www.imf.org`, `www.unfpa.org` and `www.worldbank.org` into `https`

Duplicates of `https://www.heritage.org/`
- https://www.heritage.org/index/country/bolivia/ _(bo.csv)_
- https://www.heritage.org/index/country/mali _(ml.csv)_

Duplicates of `https://www.imf.org/`
- https://www.imf.org/en/Countries/ETH/ _(et.csv)_
- https://www.imf.org/en/Countries/MMR/ _(mm.csv)_

Duplicates of `https://www.unfpa.org/`
- https://www.unfpa.org/profile/ethiopia.cfm/ _(et.csv)_
- http://www.unfpa.org/swp _(global.csv)_
- http://www.unfpa.org.py/subprogramas/salud/index.php _(py.csv)_ _404 Page Not Found_
image

Duplicates of `https://www.worldbank.org/`
- http://web.worldbank.org/archive/website01322/WEB/0__CON-2.HTM/ redirects to https://www.worldbank.org/en/home _(tm.csv)_
- http://web.worldbank.org/archive/website01322/WEB/0__MENUP.HTM/ redirects to https://www.worldbank.org/en/home _(tm.csv)_
- https://www.worldbank.org/en/country/tanzania/overview _(tz.csv)_
- https://www.worldbank.org/en/country/vietnam/ _(vn.csv)_
- https://www.worldbank.org/en/country/zimbabwe/ _(zw.csv)_

Duplicates of `https://www.aljazeera.net/` and `https://www.aljazeera.com/` - #510
- https://www.aljazeera.com/topics/country/cameroon.html _(cm.csv)_
- https://www.aljazeera.com/topics/country/algeria.html/ _(dz.csv)_
- https://sport.aljazeera.net/ redirects to https://www.aljazeera.net/sport/ _(eg.csv)_
- https://www.aljazeera.net/portal _(eg.csv & so.csv)_
- https://midan.aljazeera.net/ redirects to https://www.aljazeera.net/midan/ _(eg.csv)_
- https://blogs.aljazeera.net/ redirects to https://www.aljazeera.net/blogs/ _(eg.csv)_
- https://www.aljazeera.com/topics/country/eritrea.html _(er.csv)_
- https://www.aljazeera.com/topics/country/jordan.html/ _(jo.csv)_
- https://www.aljazeera.com/topics/country/mali.html _(ml.csv)_
- https://www.aljazeera.net/midan/ _(ps.csv)_
- http://english.aljazeera.net/ redirects to https://www.aljazeera.com/ _(th.csv)_

Duplicate of `https://www.haaretz.com/`
- https://www.haaretz.com/life/five-films-you-have-to-see-at-tel-aviv-s-international-lgbt-film-festival-1.7338266
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L505

Duplicates of `https://www.ohchr.org/`
- http://www.ohchr.org/english/bodies/hrcouncil/
- https://www.ohchr.org/en/issues/sexualorientationgender/pages/index.aspx
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L666

Duplicates of `https://en.wikipedia.org/`
- https://en.wikipedia.org/wiki/List_of_LGBT_awareness_periods
- https://en.wikipedia.org/wiki/Sex_and_gender_distinction
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L947

Additionally, I removed https://www.unwomen.org/en/news/stories?topic=f8c6fb042b184dd482c36bf10173a6aa
image

### CODE REVIEW

**Comment by RandomGuy48** [comment]
Incidentally, I found these YouTube channel by AlJazeera in ph.csv and sa.csv when I was removing duplicate links:
- https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/ph.csv#L78
- https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/sa.csv#L586

Should we also remove it or keep it?

**Comment by RandomGuy48** [comment]
Duplicates of `https://www.haaretz.com/`
- https://www.haaretz.com/life/five-films-you-have-to-see-at-tel-aviv-s-international-lgbt-film-festival-1.7338266
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L505

Duplicates of `https://www.ohchr.org/`
- http://www.ohchr.org/english/bodies/hrcouncil/
- https://www.ohchr.org/en/issues/sexualorientationgender/pages/index.aspx
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L666

Duplicates of `https://en.wikipedia.org/`
- https://en.wikipedia.org/wiki/List_of_LGBT_awareness_periods
- https://en.wikipedia.org/wiki/Sex_and_gender_distinction
https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/global.csv#L947

Additionally, I removed https://www.unwomen.org/en/news/stories?topic=f8c6fb042b184dd482c36bf10173a6aa
image

**Comment by RandomGuy48** [comment]
Incidentally, I found these YouTube channel by AlJazeera in ph.csv and sa.csv when I was removing duplicate links:
- https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/ph.csv#L78
- https://github.com/citizenlab/test-lists/blob/5d19ada974f3faa85de4c8d6ac8c2c6483d25482/lists/sa.csv#L586

Should we also remove it or keep it?

**Comment by sloncocs** [comment]
thanks so much! ❤️

**Comment by sloncocs** [comment]
I think we can remove the YouTube channel too.

**Pull request merged**
