### PR TITLE
Update mx.csv

### PR DESCRIPTION
**Pull request by carlosm2**
add media covering enforced disappearance

### CODE REVIEW

**Comment by carlosm2** [comment]
added media and NGOs covering enforced disappearance

**Comment by sloncocs** [comment]
@carlosm2 thanks so much for the contribution!

Could you please update the mx.csv in your branch? there should be no comma after 'Autonomous Server' and there should be a comma after 'citizenlab'. 

Please feel free to copy-paste lines from here:

https://espora.org/pages/About.html#About,POLR,Political Criticism,2022-07-24,citizenlab,Autonomous Server
https://sputniknews.lat/,NEWS,News Media,2023-04-24,test-lists.ooni.org contribution,
https://serapaz.org.mx/,POLR,Political Criticism,2023-08-09,citizenlab,
https://www.cemda.org.mx/,ENV,Environment,2023-08-09,citizenlab,
https://quintoelab.org/,NEWS,News Media,2023-08-09,citizenlab,
https://adondevanlosdesaparecidos.org/,POLR,Political Criticism,2023-08-09,citizenlab,

**Comment by carlosm2** [comment]
thanks for the help @sloncocs

**Comment by sloncocs** [comment]
Thank you, @carlosm2!

**Pull request merged**
