### PR TITLE
Update imap

### PR DESCRIPTION
**Pull request by sitinurliza95**
Added to my.csv:
- https://husseinhamid.com/
- https://murrayhunter.substack.com/
- https://gschqckhtpkidzxz.global.ssl.fastly.net/

### CODE REVIEW

**Comment by sitinurliza95** [comment]
Note that https://husseinhamid.com/ is owned by steadyaku47, whose other website is https://steadyaku47.com/home/, which is currently still blocked although domain is now up for sale

**Comment by sitinurliza95** [comment]
Added to my.csv

- https://psjowghndldovpnc.qsaob2yrzd.online/
- https://www.eurasiareview.com/26022024-malaysia-the-madani-government-censorship-and-propaganda-regime-oped/
- https://codeblue.galencentre.org/2024/02/26/ijn-discharging-all-civil-servants-pensioners-due-to-government-cost-cutting-measures-pensioner-failed-by-the-government/?fbclid=IwAR2V4Z6WpAo_Z6__LW33F_PRwnn6a5POdilTEg8nDzoCVXs8rnbdIndH4GM

**Comment by sloncocs** [comment]
@sitinurliza95 thanks so much for the contribution! 

the `https://www.eurasiareview.com/` and `https://codeblue.galencentre.org/` are on `https`, so we can limit them to the domain names to avoid duplicates on the test lists.

**Comment by sloncocs** [comment]
I updated both URLs, merging the PR now.

**Pull request merged**
