### PR TITLE
bd.csv list, Follow on from #809

### PR DESCRIPTION
**Pull request by Oymate**
Is reddit in the main list? If it is, will remove it.

### CODE REVIEW

**Comment by hellais** [comment]
Thanks for contributing to the test-lists!

Yes reddit is already inside of the global testing list (https://github.com/citizenlab/test-lists/blob/master/lists/global.csv#L886). Your PR also has some issues in the formatting of certain rows, where you are missing some of the required columns.

**Comment by Oymate** [comment]
Try now

**Comment by Oymate** [comment]
Remember to commit yourself, instead of merging. I don't want to be in commit list.

**Comment by Oymate** [comment]
@hellais

**Comment by Oymate** [comment]
If you commit
```
https://vk.com/,GRP,Social Networking,2021-08-30,OONI,Reported to be blocked https://bit.ly/,MISC,Miscelaneous content,2021-08-30,OONI,Reported to be blocked and link Shortener https://archive.org/,MISC,Miscelaneous content,2021-08-30,OONI,Reported to be blocked and archive website https://issuu.com/,MISC,Miscelaneous content,2021-08-30,OONI,Reported to be blocked https://mediafire.com/,FILE,File-sharing,2021-08-30,OONI,Reported to be blocked https://change.org/,POLR,Political Criticism,2021-08-30,OONI,Reported to be blocked https://ff.garena.com/,GAME,Gaming,2021-09-16,OONI,Reported to be blocked https://pubg.com/,GAME,Gaming,2021-09-16,OONI,Reported to be blocked http://iptvbd.net/,NEWS,News Media,2021-09-20,OONI,Reported to be blocked IPTV website 
```
at the end of bd.CSV, it will be lint tested. So, closing hoping you will merge.

**Comment by Oymate** [comment]
Also lots of VoIP, IPTV, e-commerce and foreign TV sites will be likely to be blocked now or in coming weeks.

**Comment by Oymate** [comment]
@hellais

**Comment by Oymate** [comment]
Don't put me in committers email list

**Comment by agrabeli** [comment]
Thank you @Oymate

**Pull request merged**
