### PR TITLE
Add URLs for captive portal tests

### PR DESCRIPTION
**Pull request by xhdix**
related to #17
It is in the MISC group because it is less important than HACK.

Note: URLs must be HTTP even if HTTPS is supported.

(msftconnecttest is still sometimes blocked in Iran.)

[OONI run](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fwww.msftncsi.com%2Fncsi.txt%22%2C%22http%3A%2F%2Fwww.msftconnecttest.com%2Fconnecttest.txt%22%2C%22http%3A%2F%2Fconnectivitycheck.gstatic.com%2Fgenerate_204%22%2C%22http%3A%2F%2Fconnectivitycheck.android.com%2Fgenerate_204%22%2C%22http%3A%2F%2Fconnect.rom.miui.com%2Fgenerate_204%22%2C%22http%3A%2F%2Fclients3.google.com%2Fgenerate_204%22%2C%22http%3A%2F%2Fdetectportal.firefox.com%2Fsuccess.txt%22%2C%22http%3A%2F%2Fwww.apple.com%2Flibrary%2Ftest%2Fsuccess.html%22%2C%22http%3A%2F%2Fnmcheck.gnome.org%2Fcheck_network_status.txt%22%2C%22http%3A%2F%2Fnetworkcheck.kde.org%2F%22%2C%22http%3A%2F%2Fstart.ubuntu.com%2Fconnectivity-check.html%22%2C%22http%3A%2F%2Fping.archlinux.org%2F%22%5D%7D&mv=1.2.0)

### CODE REVIEW

**Comment by xhdix** [comment]
It looks like that there is always an injected HTTP header `"content-encoding": ""` in the OONI backend probe service for any requests with empty HTTP body.

All `/generate_204` URLs have empty body.

Therefore, this anomaly is in the backend software, not the user network:

https://explorer.ooni.org/measurement/20210629T082442Z_webconnectivity_DE_24940_n1_0ZNAOoY63zuQWzb6?input=http%3A%2F%2Fclients3.google.com%2Fgenerate_204

**Comment by agrabeli** [comment]
@hellais please review this PR

**Comment by hellais** [comment]
Maybe they could be classified as CTRL?

**Comment by xhdix** [comment]
I had not seen it. :D 
done!

**Comment by bassosimone** [comment]
I think we SHOULD NOT merge this PR because of this issue https://github.com/ooni/probe/issues/1701

**Comment by xhdix** [comment]
I can move the other URLs (non-204) to a new PR.

**Comment by xhdix** [comment]
all done!

**Review by bassosimone — CHANGES_REQUESTED** [review]
We cannot merge until the web connectivity test helper is able to deal with this case correctly as documented at https://github.com/ooni/probe/issues/1701

**Comment by xhdix** [comment]
The user can not use the browser because the captive portal of the browser or operating system is blocked.
https://twitter.com/dyamond1317/status/1422468649097572357
image

**Comment by xhdix** [comment]
@agrabeli, fixed in the TH:
https://github.com/ooni/probe/issues/1701
and works fine:
https://explorer.ooni.org/measurement/20220619T152130Z_webconnectivity_IR_58224_n1_glag8yMfBTAY0xT8?input=http://connectivitycheck.gstatic.com/generate_204

**Pull request merged**
